title: clawson.github.io
description: >- 
  Dan Clawson Library
# domain: clawson.github.io
# url: https://clawson.github.io/library/
# baseurl: /library
github_username:  clawson

source: ./src

# architect
# midnight
# minimal

theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
